import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SEARCH_JS = ROOT / "backend/static/js/app/search.js"
CORE_JS = ROOT / "backend/static/js/app/core.js"
ROUTER_JS = ROOT / "backend/static/js/app/router.js"
INDEX_HTML = ROOT / "backend/templates/index.html"
SEARCH_API = ROOT / "backend/app/api/v1/endpoints/search.py"
OPS_API = ROOT / "backend/app/api/v1/endpoints/ops.py"
MAIN_PY = ROOT / "backend/app/main.py"


def _must_contain(text: str, needle: str, label: str, errs: list[str]) -> None:
    if needle not in text:
        errs.append(f"{label}: missing `{needle}`")


def main() -> int:
    errors: list[str] = []
    search_js = SEARCH_JS.read_text(encoding="utf-8")
    core_js = CORE_JS.read_text(encoding="utf-8")
    router_js = ROUTER_JS.read_text(encoding="utf-8")
    index_html = INDEX_HTML.read_text(encoding="utf-8")
    search_api = SEARCH_API.read_text(encoding="utf-8")
    ops_api = OPS_API.read_text(encoding="utf-8")
    main_py = MAIN_PY.read_text(encoding="utf-8")

    _must_contain(search_js, "searchFmtCardObservability: function(p)", "search.js", errors)
    _must_contain(search_js, "if (degrade > 0 || noKey > 0) level = 'degrade';", "search.js", errors)
    _must_contain(search_js, "if (ms >= 5000) level = 'slow';", "search.js", errors)
    _must_contain(search_js, "let tag = '正常';", "search.js", errors)
    _must_contain(search_js, "if (level === 'degrade') tag = '降级';", "search.js", errors)
    _must_contain(search_js, "if (level === 'slow') tag = '偏慢';", "search.js", errors)
    _must_contain(search_js, "class=\"s-obs-line\"", "search.js", errors)
    _must_contain(search_js, "class=\"s-obs-badge ${obsLevel}\"", "search.js", errors)
    _must_contain(search_js, "class=\"s-obs-text\"", "search.js", errors)
    _must_contain(search_js, "const gq = p && typeof p.generation_quality === 'object' && p.generation_quality ? p.generation_quality : null;", "search.js", errors)
    _must_contain(search_js, "const sa = p && typeof p.subtitle_audit === 'object' && p.subtitle_audit ? p.subtitle_audit : null;", "search.js", errors)
    _must_contain(search_js, "const obsQuality = obsObj && obsObj.quality ? obsObj.quality : null;", "search.js", errors)
    _must_contain(search_js, "searchToggleObsDetail: function(el)", "search.js", errors)
    _must_contain(search_js, "class=\"s-obs-detail\"", "search.js", errors)
    _must_contain(search_js, "if (t.closest('.s-obs-toggle') || t.closest('.s-obs-detail')) return;", "search.js", errors)
    _must_contain(search_js, "class=\"s-obs-line s-obs-quality-line\"", "search.js", errors)
    _must_contain(search_js, "class=\"s-obs-badge ${obsQLevel} ${obsQGradeClass}\"", "search.js", errors)
    _must_contain(search_js, "映射：A优秀 B可发布 C待优化 D建议重生成", "search.js", errors)
    _must_contain(search_js, "toggleSearchQualityMode: function()", "search.js", errors)
    _must_contain(search_js, "setSearchQualityThreshold: function()", "search.js", errors)
    _must_contain(search_js, "setSearchQualityThresholdPreset: function(v)", "search.js", errors)
    _must_contain(search_js, "searchQualityFilterMode: function()", "search.js", errors)
    _must_contain(search_js, "searchBuildRouteHash: function()", "search.js", errors)
    _must_contain(search_js, "searchSyncRouteHash: function()", "search.js", errors)
    _must_contain(search_js, "searchApplyRouteParams: function(route)", "search.js", errors)
    _must_contain(search_js, "searchQualitySortMode: function()", "search.js", errors)
    _must_contain(search_js, "searchQualitySortPrefLoad: function()", "search.js", errors)
    _must_contain(search_js, "searchQualitySortPrefSave: function()", "search.js", errors)
    _must_contain(search_js, "searchExportCustomColumnsLoad: function()", "search.js", errors)
    _must_contain(search_js, "searchExportCustomColumnsSave: function(raw)", "search.js", errors)
    _must_contain(search_js, "searchGetExportHistory: function()", "search.js", errors)
    _must_contain(search_js, "searchSetExportHistory: function(items)", "search.js", errors)
    _must_contain(search_js, "searchRecordExportHistory: function(entry)", "search.js", errors)
    _must_contain(search_js, "clearSearchExportHistory: function(force)", "search.js", errors)
    _must_contain(search_js, "searchTogglePinExportHistoryByIndex: function(index)", "search.js", errors)
    _must_contain(search_js, "searchDeleteExportHistoryByIndex: function(index)", "search.js", errors)
    _must_contain(search_js, "searchOpenExportHistoryPanel: function()", "search.js", errors)
    _must_contain(search_js, "searchCloseExportHistoryPanel: function()", "search.js", errors)
    _must_contain(search_js, "searchRenderExportHistoryPanel: function()", "search.js", errors)
    _must_contain(search_js, "searchHistoryPanelReplay: function(index)", "search.js", errors)
    _must_contain(search_js, "searchHistoryPanelTogglePin: function(index)", "search.js", errors)
    _must_contain(search_js, "searchHistoryPanelDelete: function(index)", "search.js", errors)
    _must_contain(search_js, "searchHistoryPanelClear: function()", "search.js", errors)
    _must_contain(search_js, "searchHistoryPanelSetKeyword: function(v)", "search.js", errors)
    _must_contain(search_js, "searchHistoryPanelSetRange: function(v)", "search.js", errors)
    _must_contain(search_js, "searchHistoryPanelPrevPage: function()", "search.js", errors)
    _must_contain(search_js, "searchHistoryPanelNextPage: function()", "search.js", errors)
    _must_contain(search_js, "searchHistoryPanelToggleSelect: function(index)", "search.js", errors)
    _must_contain(search_js, "searchHistoryPanelToggleSelectPage: function()", "search.js", errors)
    _must_contain(search_js, "searchHistoryPanelBulkPinOn: function()", "search.js", errors)
    _must_contain(search_js, "searchHistoryPanelBulkPinOff: function()", "search.js", errors)
    _must_contain(search_js, "searchHistoryPanelBulkDelete: function()", "search.js", errors)
    _must_contain(search_js, "searchHistoryPanelExportFilteredCsv: function()", "search.js", errors)
    _must_contain(search_js, "searchGetHistoryViews: function()", "search.js", errors)
    _must_contain(search_js, "searchSetHistoryViews: function(items)", "search.js", errors)
    _must_contain(search_js, "searchRenderHistoryViewSelect: function()", "search.js", errors)
    _must_contain(search_js, "searchSaveHistoryCurrentView: function()", "search.js", errors)
    _must_contain(search_js, "searchApplyHistoryNamedView: function(v)", "search.js", errors)
    _must_contain(search_js, "searchDeleteHistoryNamedView: function()", "search.js", errors)
    _must_contain(search_js, "searchToggleHistoryNamedViewPin: function()", "search.js", errors)
    _must_contain(search_js, "searchExportHistoryViewsJson: function()", "search.js", errors)
    _must_contain(search_js, "searchTriggerHistoryViewsImport: function()", "search.js", errors)
    _must_contain(search_js, "searchMergeImportedHistoryViews: function(items)", "search.js", errors)
    _must_contain(search_js, "searchEncodeHistoryViewsShareCode: function(payload)", "search.js", errors)
    _must_contain(search_js, "searchHistoryViewsShareCodeMaxAgeMs: function()", "search.js", errors)
    _must_contain(search_js, "searchHistoryViewsShareDigest: function(payload)", "search.js", errors)
    _must_contain(search_js, "searchDecodeHistoryViewsShareCode: function(code)", "search.js", errors)
    _must_contain(search_js, "searchExportHistoryViewsShareCode: async function()", "search.js", errors)
    _must_contain(search_js, "searchImportHistoryViewsByShareCode: function()", "search.js", errors)
    _must_contain(search_js, "searchBuildHistoryViewsShareUrl: function(code)", "search.js", errors)
    _must_contain(search_js, "searchBuildHistoryViewsShortShareUrl: function(key)", "search.js", errors)
    _must_contain(search_js, "return `${location.origin}/s/${encodeURIComponent(k)}`;", "search.js", errors)
    _must_contain(search_js, "searchCopyHistoryViewsShareLink: async function()", "search.js", errors)
    _must_contain(search_js, "searchShowHistoryViewsShareQr: async function()", "search.js", errors)
    _must_contain(search_js, "searchCloseHistoryViewsShareQr: function()", "search.js", errors)
    _must_contain(search_js, "searchParseHistoryViewsShareInput: function(raw)", "search.js", errors)
    _must_contain(search_js, "searchImportHistoryViewsByShareCodeText: function(rawCode, silent)", "search.js", errors)
    _must_contain(search_js, "searchImportHistoryViewsByShortKey: async function(rawKey, silent)", "search.js", errors)
    _must_contain(search_js, "请粘贴共享码或分享链接", "search.js", errors)
    _must_contain(search_js, "共享码已过期", "search.js", errors)
    _must_contain(search_js, "共享码校验失败，可能已被篡改", "search.js", errors)
    _must_contain(search_js, "searchImportHistoryViewsFromInput: function(input)", "search.js", errors)
    _must_contain(search_js, "searchReplayExportHistoryByIndex: function(index)", "search.js", errors)
    _must_contain(search_js, "replayLatestSearchExportHistory: function()", "search.js", errors)
    _must_contain(search_js, "searchExportTemplateLoad: function()", "search.js", errors)
    _must_contain(search_js, "searchExportTemplateSave: function()", "search.js", errors)
    _must_contain(search_js, "searchExportTemplateCurrent: function()", "search.js", errors)
    _must_contain(search_js, "searchExportAllColumns: function()", "search.js", errors)
    _must_contain(search_js, "searchExportColumnsFromCustomRaw: function(raw)", "search.js", errors)
    _must_contain(search_js, "searchExportTemplateColumns: function(tpl)", "search.js", errors)
    _must_contain(search_js, "setSearchExportTemplatePreset: function(v)", "search.js", errors)
    _must_contain(search_js, "configureSearchExportColumns: function()", "search.js", errors)
    _must_contain(search_js, "openSearchExportHistory: function()", "search.js", errors)
    _must_contain(search_js, "searchParseRouteHashParams: function(hash)", "search.js", errors)
    _must_contain(search_js, "toggleSearchQualitySort: function()", "search.js", errors)
    _must_contain(search_js, "searchSortPostsByQuality: function(posts)", "search.js", errors)
    _must_contain(search_js, "exportSearchQualityCsv: function()", "search.js", errors)
    _must_contain(search_js, "searchDownloadTextFile: function(filename, text, mime)", "search.js", errors)
    _must_contain(search_js, "searchRememberPosts: function(posts, reset)", "search.js", errors)
    _must_contain(search_js, "searchCollectPostsForView: async function(query, limit, startCursor, cfg, fetchKind)", "search.js", errors)
    _must_contain(search_js, "searchUpdateResultsSummary: function(stats)", "search.js", errors)
    _must_contain(search_js, "searchFilterPostsByQuality: function(posts)", "search.js", errors)
    _must_contain(search_js, "未找到C/D等级视频", "search.js", errors)
    _must_contain(search_js, "未找到D等级视频", "search.js", errors)
    _must_contain(search_js, "未找到无评分视频", "search.js", errors)
    _must_contain(search_js, "未找到分数低于${this.searchQualityThreshold()}的视频", "search.js", errors)

    _must_contain(index_html, ".s-obs-line", "index.html", errors)
    _must_contain(index_html, ".s-obs-badge.ok", "index.html", errors)
    _must_contain(index_html, ".s-obs-badge.degrade", "index.html", errors)
    _must_contain(index_html, ".s-obs-badge.slow", "index.html", errors)
    _must_contain(index_html, ".s-obs-text", "index.html", errors)
    _must_contain(index_html, ".s-obs-toggle", "index.html", errors)
    _must_contain(index_html, ".s-obs-detail", "index.html", errors)
    _must_contain(index_html, ".s-obs-badge.q-a", "index.html", errors)
    _must_contain(index_html, ".s-obs-badge.q-d", "index.html", errors)
    _must_contain(index_html, ".s-obs-quality-line:hover + .s-obs-hover", "index.html", errors)
    _must_contain(index_html, ".search-filter-pill", "index.html", errors)
    _must_contain(index_html, ".search-filter-pill.active", "index.html", errors)
    _must_contain(index_html, ".search-filter-select", "index.html", errors)
    _must_contain(index_html, "id=\"search_filter_quality_mode\"", "index.html", errors)
    _must_contain(index_html, "id=\"search_filter_quality_sort\"", "index.html", errors)
    _must_contain(index_html, "id=\"search_filter_quality_threshold_select\"", "index.html", errors)
    _must_contain(index_html, "id=\"search_export_template_select\"", "index.html", errors)
    _must_contain(index_html, "id=\"search_filter_quality_threshold\"", "index.html", errors)
    _must_contain(index_html, "id=\"search_export_quality_columns\"", "index.html", errors)
    _must_contain(index_html, "id=\"search_export_quality_csv\"", "index.html", errors)
    _must_contain(index_html, "id=\"search_export_quality_history\"", "index.html", errors)
    _must_contain(index_html, "id=\"search_export_quality_replay\"", "index.html", errors)
    _must_contain(index_html, "id=\"search_export_quality_clear\"", "index.html", errors)
    _must_contain(index_html, "id=\"search_export_history_panel\"", "index.html", errors)
    _must_contain(index_html, "id=\"search_export_history_panel_body\"", "index.html", errors)
    _must_contain(index_html, "id=\"search_export_history_filter_input\"", "index.html", errors)
    _must_contain(index_html, "id=\"search_export_history_range_select\"", "index.html", errors)
    _must_contain(index_html, "id=\"search_export_history_view_select\"", "index.html", errors)
    _must_contain(index_html, "data-fn=\"searchSaveHistoryCurrentView\"", "index.html", errors)
    _must_contain(index_html, "data-fn=\"searchToggleHistoryNamedViewPin\"", "index.html", errors)
    _must_contain(index_html, "data-fn=\"searchDeleteHistoryNamedView\"", "index.html", errors)
    _must_contain(index_html, "data-fn=\"searchExportHistoryViewsJson\"", "index.html", errors)
    _must_contain(index_html, "data-fn=\"searchTriggerHistoryViewsImport\"", "index.html", errors)
    _must_contain(index_html, "data-fn=\"searchExportHistoryViewsShareCode\"", "index.html", errors)
    _must_contain(index_html, "data-fn=\"searchImportHistoryViewsByShareCode\"", "index.html", errors)
    _must_contain(index_html, "data-fn=\"searchCopyHistoryViewsShareLink\"", "index.html", errors)
    _must_contain(index_html, "data-fn=\"searchShowHistoryViewsShareQr\"", "index.html", errors)
    _must_contain(index_html, "id=\"search_history_views_import_input\"", "index.html", errors)
    _must_contain(index_html, "id=\"search_history_views_qr_panel\"", "index.html", errors)
    _must_contain(index_html, "id=\"search_history_views_qr_img\"", "index.html", errors)
    _must_contain(index_html, "id=\"search_history_views_qr_link\"", "index.html", errors)
    _must_contain(index_html, ".search-share-qr-panel", "index.html", errors)
    _must_contain(index_html, "searchApplyHistoryNamedView&&window.app.searchApplyHistoryNamedView(this.value)", "index.html", errors)
    _must_contain(index_html, "data-fn=\"searchHistoryPanelBulkPinOn\"", "index.html", errors)
    _must_contain(index_html, "data-fn=\"searchHistoryPanelBulkPinOff\"", "index.html", errors)
    _must_contain(index_html, "data-fn=\"searchHistoryPanelExportFilteredCsv\"", "index.html", errors)
    _must_contain(index_html, "id=\"search_export_history_panel_pager\"", "index.html", errors)
    _must_contain(index_html, ".search-export-panel", "index.html", errors)
    _must_contain(index_html, ".search-export-filter", "index.html", errors)
    _must_contain(index_html, ".search-export-pager", "index.html", errors)
    _must_contain(index_html, "id=\"search_results_summary_main\"", "index.html", errors)
    _must_contain(index_html, "id=\"search_results_summary_sub\"", "index.html", errors)
    _must_contain(core_js, "pendingSearchRoute", "core.js", errors)
    _must_contain(core_js, "qs.get('kw')", "core.js", errors)
    _must_contain(core_js, "qs.get('quality_filter')", "core.js", errors)
    _must_contain(core_js, "qs.get('qsort')", "core.js", errors)
    _must_contain(core_js, "qs.get('svc')", "core.js", errors)
    _must_contain(core_js, "qs.get('svk')", "core.js", errors)
    _must_contain(router_js, "searchApplyRouteParams", "router.js", errors)

    _must_contain(search_api, "cover_metrics", "search.py", errors)
    _must_contain(search_api, "subtitle_audit", "search.py", errors)
    _must_contain(search_api, "generation_quality", "search.py", errors)
    _must_contain(search_api, "analysis_audit", "search.py", errors)
    _must_contain(search_api, "@router.post(\"/share-views\"", "search.py", errors)
    _must_contain(search_api, "@router.get(\"/share-views/{share_key}\"", "search.py", errors)
    _must_contain(search_api, "_record_share_metric(\"create_ok\"", "search.py", errors)
    _must_contain(search_api, "_record_share_metric(\"resolve_ok\"", "search.py", errors)
    _must_contain(search_api, "search:share:views:metrics:samples", "search.py", errors)
    _must_contain(ops_api, "@router.get(\"/admin/search-share/metrics\")", "ops.py", errors)
    _must_contain(ops_api, "\"samples\": samples", "ops.py", errors)
    _must_contain(ops_api, "\"create_client_error_total\"", "ops.py", errors)
    _must_contain(ops_api, "\"resolve_server_error_total\"", "ops.py", errors)
    _must_contain(ops_api, "sample_event_kw: str = Query(\"\", max_length=64)", "ops.py", errors)
    _must_contain(ops_api, "sample_key_kw: str = Query(\"\", max_length=64)", "ops.py", errors)
    _must_contain(ops_api, "sample_window_hours: int = Query(168, ge=1, le=24 * 30)", "ops.py", errors)
    _must_contain(ops_api, "sample_only_errors: bool = Query(False)", "ops.py", errors)
    _must_contain(ops_api, "\"sample_stats\": sample_stats", "ops.py", errors)
    _must_contain(ops_api, "\"status_counts\": status_counts", "ops.py", errors)
    _must_contain(ops_api, "\"health_level\": str(health_level)", "ops.py", errors)
    _must_contain(ops_api, "\"health_reason\": str(health_reason)", "ops.py", errors)
    _must_contain(ops_api, "\"health_alert\": bool(health_alert)", "ops.py", errors)
    _must_contain(ops_api, "\"alert_level\": str(alert_level)", "ops.py", errors)
    _must_contain(ops_api, "\"suggested_action\": str(suggested_action)", "ops.py", errors)
    _must_contain(ops_api, "\"action_priority\": int(action_priority)", "ops.py", errors)
    _must_contain(ops_api, "\"recommended_recheck_minutes\": int(recommended_recheck_minutes)", "ops.py", errors)
    _must_contain(ops_api, "\"action_due_ts\": int(action_due_ts)", "ops.py", errors)
    _must_contain(ops_api, "\"action_status\": str(action_status)", "ops.py", errors)
    _must_contain(ops_api, "\"action_due_in_seconds\": int(action_due_in_seconds)", "ops.py", errors)
    _must_contain(ops_api, "\"action_overdue\": bool(action_overdue)", "ops.py", errors)
    _must_contain(ops_api, "\"action_overdue_minutes\": int(action_overdue_minutes)", "ops.py", errors)
    _must_contain(ops_api, "\"breach_level\": str(breach_level)", "ops.py", errors)
    _must_contain(ops_api, "\"escalation_hint\": str(escalation_hint)", "ops.py", errors)
    _must_contain(ops_api, "\"escalation_required\": bool(escalation_required)", "ops.py", errors)
    _must_contain(ops_api, "\"escalation_deadline_ts\": int(escalation_deadline_ts)", "ops.py", errors)
    _must_contain(ops_api, "\"escalation_due_in_seconds\": int(escalation_due_in_seconds)", "ops.py", errors)
    _must_contain(ops_api, "\"escalation_urgency\": str(escalation_urgency)", "ops.py", errors)
    _must_contain(ops_api, "\"escalation_window_overdue\": bool(escalation_window_overdue)", "ops.py", errors)
    _must_contain(ops_api, "\"escalation_stage\": str(escalation_stage)", "ops.py", errors)
    _must_contain(ops_api, "\"escalation_sla_level\": str(escalation_sla_level)", "ops.py", errors)
    _must_contain(ops_api, "\"escalation_playbook_action\": str(escalation_playbook_action)", "ops.py", errors)
    _must_contain(ops_api, "\"escalation_target_response_minutes\": int(escalation_target_response_minutes)", "ops.py", errors)
    _must_contain(ops_api, "\"escalation_owner_role\": str(escalation_owner_role)", "ops.py", errors)
    _must_contain(ops_api, "\"escalation_ack_status\": str(escalation_ack_status)", "ops.py", errors)
    _must_contain(ops_api, "\"escalation_ack_due_ts\": int(escalation_ack_due_ts)", "ops.py", errors)
    _must_contain(ops_api, "\"escalation_ack_due_in_seconds\": int(escalation_ack_due_in_seconds)", "ops.py", errors)
    _must_contain(ops_api, "\"ack_breach_level\": str(ack_breach_level)", "ops.py", errors)
    _must_contain(ops_api, "\"ack_nudge_action\": str(ack_nudge_action)", "ops.py", errors)
    _must_contain(ops_api, "\"ack_nudge_channel\": str(ack_nudge_channel)", "ops.py", errors)
    _must_contain(ops_api, "\"ack_nudge_urgency\": str(ack_nudge_urgency)", "ops.py", errors)
    _must_contain(ops_api, "\"ack_nudge_retry_count\": int(ack_nudge_retry_count)", "ops.py", errors)
    _must_contain(ops_api, "\"ack_nudge_next_ts\": int(ack_nudge_next_ts)", "ops.py", errors)
    _must_contain(ops_api, "\"ack_nudge_next_in_seconds\": int(ack_nudge_next_in_seconds)", "ops.py", errors)
    _must_contain(ops_api, "\"ack_nudge_backoff_minutes\": int(ack_nudge_backoff_minutes)", "ops.py", errors)
    _must_contain(ops_api, "\"ack_nudge_state\": str(ack_nudge_state)", "ops.py", errors)
    _must_contain(ops_api, "\"ack_nudge_attempted_count\": int(ack_nudge_attempted_count)", "ops.py", errors)
    _must_contain(ops_api, "\"ack_nudge_success_rate\": float(ack_nudge_success_rate)", "ops.py", errors)
    _must_contain(ops_api, "\"ack_nudge_quality_grade\": str(ack_nudge_quality_grade)", "ops.py", errors)
    _must_contain(ops_api, "\"ack_nudge_recommendation\": str(ack_nudge_recommendation)", "ops.py", errors)
    _must_contain(ops_api, "\"ack_nudge_quality_score\": int(ack_nudge_quality_score)", "ops.py", errors)
    _must_contain(ops_api, "\"ack_nudge_quality_confidence\": str(ack_nudge_quality_confidence)", "ops.py", errors)
    _must_contain(ops_api, "\"ack_nudge_quality_prev_score\": int(ack_nudge_quality_prev_score)", "ops.py", errors)
    _must_contain(ops_api, "\"ack_nudge_quality_trend_delta\": int(ack_nudge_quality_trend_delta)", "ops.py", errors)
    _must_contain(ops_api, "\"ack_nudge_quality_trend_direction\": str(ack_nudge_quality_trend_direction)", "ops.py", errors)
    _must_contain(ops_api, "\"ack_nudge_quality_trend_confidence\": str(ack_nudge_quality_trend_confidence)", "ops.py", errors)
    _must_contain(ops_api, "\"ack_nudge_quality_trend_alert_level\": str(ack_nudge_quality_trend_alert_level)", "ops.py", errors)
    _must_contain(ops_api, "\"ack_nudge_quality_trend_recommendation\": str(ack_nudge_quality_trend_recommendation)", "ops.py", errors)
    _must_contain(ops_api, "\"trend_escalation_required\": bool(trend_escalation_required)", "ops.py", errors)
    _must_contain(ops_api, "\"trend_escalation_stage\": str(trend_escalation_stage)", "ops.py", errors)
    _must_contain(ops_api, "\"trend_escalation_owner_role\": str(trend_escalation_owner_role)", "ops.py", errors)
    _must_contain(ops_api, "\"trend_escalation_playbook_action\": str(trend_escalation_playbook_action)", "ops.py", errors)
    _must_contain(ops_api, "\"trend_escalation_target_response_minutes\": int(trend_escalation_target_response_minutes)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_required\": bool(effective_escalation_required)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_owner_role\": str(effective_escalation_owner_role)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_playbook_action\": str(effective_escalation_playbook_action)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_target_response_minutes\": int(effective_escalation_target_response_minutes)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_source\": str(effective_escalation_source)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_urgency\": str(effective_escalation_urgency)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_due_ts\": int(effective_escalation_due_ts)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_due_in_seconds\": int(effective_escalation_due_in_seconds)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_overdue\": bool(effective_escalation_overdue)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_due_in_minutes\": int(effective_escalation_due_in_minutes)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_breach_level\": str(effective_escalation_breach_level)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_followup_action\": str(effective_escalation_followup_action)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_followup_required\": bool(effective_escalation_followup_required)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_followup_due_minutes\": int(effective_escalation_followup_due_minutes)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_followup_due_ts\": int(effective_escalation_followup_due_ts)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_followup_due_in_seconds\": int(effective_escalation_followup_due_in_seconds)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_followup_status\": str(effective_escalation_followup_status)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_followup_channel\": str(effective_escalation_followup_channel)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_followup_urgency\": str(effective_escalation_followup_urgency)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_followup_retry_count\": int(effective_escalation_followup_retry_count)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_followup_backoff_minutes\": int(effective_escalation_followup_backoff_minutes)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_followup_next_ts\": int(effective_escalation_followup_next_ts)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_followup_next_in_seconds\": int(effective_escalation_followup_next_in_seconds)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_followup_state\": str(effective_escalation_followup_state)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_followup_quality_score\": int(effective_escalation_followup_quality_score)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_followup_quality_grade\": str(effective_escalation_followup_quality_grade)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_followup_quality_recommendation\": str(effective_escalation_followup_quality_recommendation)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_followup_quality_prev_score\": int(effective_escalation_followup_quality_prev_score)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_followup_quality_trend_delta\": int(effective_escalation_followup_quality_trend_delta)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_followup_quality_trend_direction\": str(effective_escalation_followup_quality_trend_direction)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_followup_quality_trend_confidence\": str(effective_escalation_followup_quality_trend_confidence)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_followup_quality_trend_alert_level\": str(effective_escalation_followup_quality_trend_alert_level)", "ops.py", errors)
    _must_contain(ops_api, "\"effective_escalation_followup_quality_trend_recommendation\": str(effective_escalation_followup_quality_trend_recommendation)", "ops.py", errors)
    _must_contain(ops_api, "\"action_bucket\": str(action_bucket)", "ops.py", errors)
    _must_contain(ops_api, "\"action_note\": str(action_note)", "ops.py", errors)
    _must_contain(ops_api, "\"health_trend\": {", "ops.py", errors)
    _must_contain(ops_api, "\"direction\": str(trend_direction)", "ops.py", errors)
    _must_contain(ops_api, "\"confidence\": str(trend_confidence)", "ops.py", errors)
    _must_contain(ops_api, "\"alert\": bool(trend_alert)", "ops.py", errors)
    _must_contain(ops_api, "\"status_rates\": {\"ok\": float(ok_rate), \"err4xx\": float(err4_rate), \"err5xx\": float(err5_rate)}", "ops.py", errors)
    _must_contain(ops_api, "\"event_top\": [{\"event\": k, \"count\": int(v)}", "ops.py", errors)
    _must_contain(main_py, "@app.api_route(\"/s/{share_key}\"", "main.py", errors)

    if errors:
        sys.stdout.write("SEARCH_CARD_OBSERVABILITY_REGRESSION_FAIL\n")
        for e in errors:
            sys.stdout.write(f"- {e}\n")
        return 1
    sys.stdout.write("SEARCH_CARD_OBSERVABILITY_REGRESSION_OK\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
