TOKEN_BUCKET = (
    "local key=KEYS[1];"
    "local rate=tonumber(ARGV[1]);"
    "local burst=tonumber(ARGV[2]);"
    "local now=tonumber(ARGV[3]);"
    "local cost=tonumber(ARGV[4]);"
    "local data=redis.call('HMGET',key,'tokens','ts');"
    "local tokens=tonumber(data[1]);"
    "local ts=tonumber(data[2]);"
    "if (not tokens) then tokens=burst; ts=now; end;"
    "local delta=now-ts; if delta<0 then delta=0 end;"
    "tokens=math.min(burst, tokens + (delta*rate));"
    "local ok=0;"
    "if tokens>=cost then tokens=tokens-cost; ok=1; end;"
    "redis.call('HMSET',key,'tokens',tokens,'ts',now);"
    "local ttl=math.ceil((burst/rate)+2); if ttl<2 then ttl=2 end;"
    "redis.call('EXPIRE',key,ttl);"
    "return ok;"
)
